=== Alfresco/alfresco-java-sdk/alfresco-java-event-api/alfresco-java-event-api-model/src/main/resources/json-schema/nodeUpdated.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {
    "Resource" : {
      "type" : "object"
    }
  },
  "type" : "object",
  "properties" : {
    "specversion" : {
      "type" : "string"
    },
    "type" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "source" : {
      "type" : "string"
    },
    "time" : {
      "type" : "string"
    },
    "dataschema" : {
      "type" : "string"
    },
    "datacontenttype" : {
      "type" : "string"
    },
    "data" : {
      "type" : "object",
      "properties" : {
        "eventGroupId" : {
          "type" : "string"
        },
        "resource" : {
          "$ref" : "#/$defs/Resource"
        },
        "resourceBefore" : {
          "$ref" : "#/$defs/Resource"
        }
      },
      "required" : [ "eventGroupId", "resource", "resourceBefore" ]
    }
  },
  "required" : [ "specversion", "type", "id", "source", "time", "dataschema", "datacontenttype", "data" ]
}

=== Alfresco/alfresco-java-sdk/alfresco-java-event-api/alfresco-java-event-api-model/src/test/resources/NodeUpdatedEvent.json
{
  "specversion": "1.0",
  "type": "org.alfresco.event.node.Updated",
  "id": "df708027-e0a8-4b30-92a5-0d19235a7800",
  "source": "/f6d21231-618e-4f12-a920-e498660c5b9d",
  "time": "2020-04-27T14:25:59.855866+01:00",
  "dataschema": "https://api.alfresco.com/schema/event/repo/v1/nodeUpdated",
  "datacontenttype": "application/json",
  "data": {
    "eventGroupId": "ce852a52-609e-4b7d-8438-04e211fd76a0",
    "resource": {
      "@type": "NodeResource",
      "id": "d366f805-853f-46ac-a81c-af9c257ee876",
      "name": "testFile.txt",
      "nodeType": "cm:content",
      "isFolder": false,
      "isFile": true,
      "createdByUser": {
        "id": "john.doe",
        "displayName": "John Doe"
      },
      "createdAt": "2020-04-27T14:25:59.852475+01:00",
      "modifiedByUser": {
        "id": "jane.doe",
        "displayName": "Jane Doe"
      },
      "modifiedAt": "2020-04-27T14:25:59.854153+01:00",
      "content": {
        "mimeType": "text/plain",
        "sizeInBytes": 16,
        "encoding": "UTF-8"
      },
      "primaryHierarchy": [
        "521aac1c-20eb-444b-a137-2da3d35ee1a8",
        "2641bbe1-39ff-44dc-b47f-736552ad46cc"
      ],
      "properties": {
        "cm:description": "test description.",
        "cm:title": "test title2"
      },
      "aspectNames": [
        "cm:titled",
        "cm:auditable"
      ]
    },
    "resourceBefore": {
      "@type": "NodeResource",
      "modifiedByUser": {
        "id": "jane.doe",
        "displayName": "Jane Doe"
      },
      "modifiedAt": "2020-04-27T14:25:59.854558+01:00",
      "properties": {
        "cm:title": "test title"
      }
    }
  }
}
