=== Alfresco/alfresco-java-sdk/alfresco-java-event-api/alfresco-java-event-api-model/src/main/resources/json-schema/peerAssocCreated.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {
    "PeerAssocInfo" : {
      "type" : "object",
      "properties" : {
        "id" : {
          "type" : "string"
        }
      }
    }
  },
  "type" : "object",
  "properties" : {
    "specversion" : {
      "type" : "string"
    },
    "type" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "source" : {
      "type" : "string"
    },
    "time" : {
      "type" : "string"
    },
    "dataschema" : {
      "type" : "string"
    },
    "datacontenttype" : {
      "type" : "string"
    },
    "data" : {
      "type" : "object",
      "properties" : {
        "eventGroupId" : {
          "type" : "string"
        },
        "resource" : {
          "type" : "object",
          "properties" : {
            "assocType" : {
              "type" : "string"
            },
            "source" : {
              "$ref" : "#/$defs/PeerAssocInfo"
            },
            "target" : {
              "$ref" : "#/$defs/PeerAssocInfo"
            }
          },
          "required" : [ "assocType", "source", "target" ]
        }
      },
      "required" : [ "eventGroupId", "resource" ]
    }
  },
  "required" : [ "specversion", "type", "id", "source", "time", "dataschema", "datacontenttype", "data" ]
}

=== Alfresco/alfresco-java-sdk/alfresco-java-event-api/alfresco-java-event-api-model/src/test/resources/PeerAssocCreated.json
{
  "specversion": "1.0",
  "type": "org.alfresco.event.assoc.peer.Created",
  "id": "8677a369-a30d-469e-b313-e5bf1b590c8e",
  "source": "/f6d21231-618e-4f12-a920-e498660c5b9d",
  "time": "2020-05-28T10:36:21.291392+01:00",
  "dataschema": "https://api.alfresco.com/schema/event/repo/v1/peerAssocCreated",
  "datacontenttype": "application/json",
  "data": {
    "eventGroupId": "b23f75d0-45da-40d1-9063-eb800a4f2444",
    "resource": {
      "@type": "PeerAssociationResource",
      "assocType": "cm:references",
      "source": {
        "id": "d323671c-9bd0-483e-8471-bd64cea73c09"
      },
      "target": {
        "id": "595c55b0-64b3-4f1b-95f8-c1cc6b3843a2"
      }
    }
  }
}
